--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CANE
--------------------------------------------------------

  CREATE TABLE "MARTINO"."CANE" 
   (	"ID_CANE" NUMBER(10,0), 
	"TAGLIA" VARCHAR2(10 BYTE), 
	"CHIP" VARCHAR2(10 BYTE), 
	"SESSO" VARCHAR2(10 BYTE), 
	"DATA_NASCITA" DATE, 
	"PEDEGREE" NUMBER(3,0), 
	"ID_UTENTE" NUMBER(10,0), 
	"ID_RAZZA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOG_FRIENDLY
--------------------------------------------------------

  CREATE TABLE "MARTINO"."DOG_FRIENDLY" 
   (	"ID_FRIENDL" NUMBER(10,0), 
	"RAZZA" VARCHAR2(10 BYTE), 
	"ID_ATTIVITA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RAZZA
--------------------------------------------------------

  CREATE TABLE "MARTINO"."RAZZA" 
   (	"ID_RAZZA" NUMBER(10,0), 
	"RAZZA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RUOLO
--------------------------------------------------------

  CREATE TABLE "MARTINO"."RUOLO" 
   (	"ID_RUOLO" NUMBER(10,0), 
	"NOME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_ATTIVITA
--------------------------------------------------------

  CREATE TABLE "MARTINO"."TIPO_ATTIVITA" 
   (	"ID_ATTIVITA" NUMBER(10,0), 
	"TIPO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTENTE
--------------------------------------------------------

  CREATE TABLE "MARTINO"."UTENTE" 
   (	"ID_UTENTE" NUMBER(10,0), 
	"NOME" VARCHAR2(10 BYTE), 
	"COGNOME" VARCHAR2(10 BYTE), 
	"SESSO" VARCHAR2(10 BYTE), 
	"USERNAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"INDIRIZZO" VARCHAR2(10 BYTE), 
	"VERIFICATO" NUMBER(3,0), 
	"MAIL" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTENTE_RUOLO
--------------------------------------------------------

  CREATE TABLE "MARTINO"."UTENTE_RUOLO" 
   (	"ID_RUOLO" NUMBER(10,0), 
	"ID_UTENTE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MARTINO.CANE
SET DEFINE OFF;
REM INSERTING into MARTINO.DOG_FRIENDLY
SET DEFINE OFF;
REM INSERTING into MARTINO.RAZZA
SET DEFINE OFF;
REM INSERTING into MARTINO.RUOLO
SET DEFINE OFF;
REM INSERTING into MARTINO.TIPO_ATTIVITA
SET DEFINE OFF;
REM INSERTING into MARTINO.UTENTE
SET DEFINE OFF;
REM INSERTING into MARTINO.UTENTE_RUOLO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007585
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007585" ON "MARTINO"."CANE" ("ID_CANE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007594
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007594" ON "MARTINO"."DOG_FRIENDLY" ("ID_FRIENDL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007595
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007595" ON "MARTINO"."DOG_FRIENDLY" ("RAZZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007579
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007579" ON "MARTINO"."RAZZA" ("ID_RAZZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007561
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007561" ON "MARTINO"."RUOLO" ("ID_RUOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007562
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007562" ON "MARTINO"."RUOLO" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007590
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007590" ON "MARTINO"."TIPO_ATTIVITA" ("ID_ATTIVITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007591
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007591" ON "MARTINO"."TIPO_ATTIVITA" ("TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007572
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007572" ON "MARTINO"."UTENTE" ("ID_UTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007573
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007573" ON "MARTINO"."UTENTE" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007574
--------------------------------------------------------

  CREATE UNIQUE INDEX "MARTINO"."SYS_C007574" ON "MARTINO"."UTENTE_RUOLO" ("ID_UTENTE", "ID_RUOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CANE
--------------------------------------------------------

  ALTER TABLE "MARTINO"."CANE" ADD PRIMARY KEY ("ID_CANE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."CANE" MODIFY ("PEDEGREE" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."CANE" MODIFY ("DATA_NASCITA" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."CANE" MODIFY ("SESSO" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."CANE" MODIFY ("TAGLIA" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."CANE" MODIFY ("ID_CANE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOG_FRIENDLY
--------------------------------------------------------

  ALTER TABLE "MARTINO"."DOG_FRIENDLY" ADD UNIQUE ("RAZZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."DOG_FRIENDLY" ADD PRIMARY KEY ("ID_FRIENDL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."DOG_FRIENDLY" MODIFY ("RAZZA" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."DOG_FRIENDLY" MODIFY ("ID_FRIENDL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RAZZA
--------------------------------------------------------

  ALTER TABLE "MARTINO"."RAZZA" ADD PRIMARY KEY ("ID_RAZZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."RAZZA" MODIFY ("RAZZA" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."RAZZA" MODIFY ("ID_RAZZA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUOLO
--------------------------------------------------------

  ALTER TABLE "MARTINO"."RUOLO" ADD UNIQUE ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."RUOLO" ADD PRIMARY KEY ("ID_RUOLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."RUOLO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."RUOLO" MODIFY ("ID_RUOLO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_ATTIVITA
--------------------------------------------------------

  ALTER TABLE "MARTINO"."TIPO_ATTIVITA" ADD UNIQUE ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."TIPO_ATTIVITA" ADD PRIMARY KEY ("ID_ATTIVITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."TIPO_ATTIVITA" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."TIPO_ATTIVITA" MODIFY ("ID_ATTIVITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTENTE
--------------------------------------------------------

  ALTER TABLE "MARTINO"."UTENTE" ADD UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."UTENTE" ADD PRIMARY KEY ("ID_UTENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("VERIFICATO" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("INDIRIZZO" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("SESSO" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "MARTINO"."UTENTE" MODIFY ("ID_UTENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTENTE_RUOLO
--------------------------------------------------------

  ALTER TABLE "MARTINO"."UTENTE_RUOLO" ADD PRIMARY KEY ("ID_UTENTE", "ID_RUOLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
